apiVersion: v1
kind: Service
metadata:
  name: admin-ui-service
spec:
  type: LoadBalancer
  selector:
    app: admin-ui-service
  ports:
    - protocol: TCP
      port: 4000         
      targetPort: 8080